/*
 * This file is generated by jOOQ.
 */
package com.allane.mobility.persistence;


import com.allane.mobility.persistence.tables.AmCustomer;
import com.allane.mobility.persistence.tables.AmCustomerLeasingContract;
import com.allane.mobility.persistence.tables.AmLeasingContract;
import com.allane.mobility.persistence.tables.AmUser;
import com.allane.mobility.persistence.tables.AmVehicle;
import com.allane.mobility.persistence.tables.FlywaySchemaHistory;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Allmob extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>allmob</code>
     */
    public static final Allmob ALLMOB = new Allmob();

    /**
     * The table <code>allmob.am_customer</code>.
     */
    public final AmCustomer AM_CUSTOMER = AmCustomer.AM_CUSTOMER;

    /**
     * The table <code>allmob.am_customer_leasing_contract</code>.
     */
    public final AmCustomerLeasingContract AM_CUSTOMER_LEASING_CONTRACT = AmCustomerLeasingContract.AM_CUSTOMER_LEASING_CONTRACT;

    /**
     * The table <code>allmob.am_leasing_contract</code>.
     */
    public final AmLeasingContract AM_LEASING_CONTRACT = AmLeasingContract.AM_LEASING_CONTRACT;

    /**
     * The table <code>allmob.am_user</code>.
     */
    public final AmUser AM_USER = AmUser.AM_USER;

    /**
     * The table <code>allmob.am_vehicle</code>.
     */
    public final AmVehicle AM_VEHICLE = AmVehicle.AM_VEHICLE;

    /**
     * The table <code>allmob.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * No further instances allowed
     */
    private Allmob() {
        super("allmob", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AmCustomer.AM_CUSTOMER,
            AmCustomerLeasingContract.AM_CUSTOMER_LEASING_CONTRACT,
            AmLeasingContract.AM_LEASING_CONTRACT,
            AmUser.AM_USER,
            AmVehicle.AM_VEHICLE,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY
        );
    }
}
