/*
 * This file is generated by jOOQ.
 */
package com.allane.mobility.persistence;


import com.allane.mobility.persistence.tables.AmUser;
import com.allane.mobility.persistence.tables.FlywaySchemaHistory;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Allmob extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>allmob</code>
     */
    public static final Allmob ALLMOB = new Allmob();

    /**
     * The table <code>allmob.am_user</code>.
     */
    public final AmUser AM_USER = AmUser.AM_USER;

    /**
     * The table <code>allmob.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * No further instances allowed
     */
    private Allmob() {
        super("allmob", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AmUser.AM_USER,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY
        );
    }
}
