/*
 * This file is generated by jOOQ.
 */
package com.allane.mobility.persistence;


import com.allane.mobility.persistence.tables.AmUser;
import com.allane.mobility.persistence.tables.FlywaySchemaHistory;
import com.allane.mobility.persistence.tables.records.AmUserRecord;
import com.allane.mobility.persistence.tables.records.FlywaySchemaHistoryRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * allmob.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AmUserRecord> KEY_AM_USER_PRIMARY = Internal.createUniqueKey(AmUser.AM_USER, DSL.name("KEY_am_user_PRIMARY"), new TableField[] { AmUser.AM_USER.ID_USER, AmUser.AM_USER.NAME, AmUser.AM_USER.SURNAME }, true);
    public static final UniqueKey<FlywaySchemaHistoryRecord> KEY_FLYWAY_SCHEMA_HISTORY_PRIMARY = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("KEY_flyway_schema_history_PRIMARY"), new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
}
