/*
 * This file is generated by jOOQ.
 */
package com.allane.mobility.persistence;


import com.allane.mobility.persistence.tables.AmUser;
import com.allane.mobility.persistence.tables.FlywaySchemaHistory;


/**
 * Convenience access to all tables in allmob.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>allmob.am_user</code>.
     */
    public static final AmUser AM_USER = AmUser.AM_USER;

    /**
     * The table <code>allmob.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;
}
