/*
 * This file is generated by jOOQ.
 */
package com.allane.mobility.persistence;


import com.allane.mobility.persistence.tables.AmCustomer;
import com.allane.mobility.persistence.tables.AmCustomerLeasingContract;
import com.allane.mobility.persistence.tables.AmLeasingContract;
import com.allane.mobility.persistence.tables.AmUser;
import com.allane.mobility.persistence.tables.AmVehicle;
import com.allane.mobility.persistence.tables.FlywaySchemaHistory;


/**
 * Convenience access to all tables in allmob.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>allmob.am_customer</code>.
     */
    public static final AmCustomer AM_CUSTOMER = AmCustomer.AM_CUSTOMER;

    /**
     * The table <code>allmob.am_customer_leasing_contract</code>.
     */
    public static final AmCustomerLeasingContract AM_CUSTOMER_LEASING_CONTRACT = AmCustomerLeasingContract.AM_CUSTOMER_LEASING_CONTRACT;

    /**
     * The table <code>allmob.am_leasing_contract</code>.
     */
    public static final AmLeasingContract AM_LEASING_CONTRACT = AmLeasingContract.AM_LEASING_CONTRACT;

    /**
     * The table <code>allmob.am_user</code>.
     */
    public static final AmUser AM_USER = AmUser.AM_USER;

    /**
     * The table <code>allmob.am_vehicle</code>.
     */
    public static final AmVehicle AM_VEHICLE = AmVehicle.AM_VEHICLE;

    /**
     * The table <code>allmob.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;
}
