/*
 * This file is generated by jOOQ.
 */
package com.allane.mobility.persistence.tables.records;


import com.allane.mobility.persistence.tables.AmCustomer;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AmCustomerRecord extends UpdatableRecordImpl<AmCustomerRecord> implements Record6<UShort, String, String, LocalDateTime, LocalDateTime, UShort> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>allmob.am_customer.ID_customer</code>.
     */
    public void setIdCustomer(UShort value) {
        set(0, value);
    }

    /**
     * Getter for <code>allmob.am_customer.ID_customer</code>.
     */
    public UShort getIdCustomer() {
        return (UShort) get(0);
    }

    /**
     * Setter for <code>allmob.am_customer.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>allmob.am_customer.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>allmob.am_customer.surname</code>.
     */
    public void setSurname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>allmob.am_customer.surname</code>.
     */
    public String getSurname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>allmob.am_customer.birthday</code>.
     */
    public void setBirthday(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>allmob.am_customer.birthday</code>.
     */
    public LocalDateTime getBirthday() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>allmob.am_customer.changed</code>.
     */
    public void setChanged(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>allmob.am_customer.changed</code>.
     */
    public LocalDateTime getChanged() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>allmob.am_customer.ID_user_change</code>.
     */
    public void setIdUserChange(UShort value) {
        set(5, value);
    }

    /**
     * Getter for <code>allmob.am_customer.ID_user_change</code>.
     */
    public UShort getIdUserChange() {
        return (UShort) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<UShort, String, String> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<UShort, String, String, LocalDateTime, LocalDateTime, UShort> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<UShort, String, String, LocalDateTime, LocalDateTime, UShort> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<UShort> field1() {
        return AmCustomer.AM_CUSTOMER.ID_CUSTOMER;
    }

    @Override
    public Field<String> field2() {
        return AmCustomer.AM_CUSTOMER.NAME;
    }

    @Override
    public Field<String> field3() {
        return AmCustomer.AM_CUSTOMER.SURNAME;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return AmCustomer.AM_CUSTOMER.BIRTHDAY;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return AmCustomer.AM_CUSTOMER.CHANGED;
    }

    @Override
    public Field<UShort> field6() {
        return AmCustomer.AM_CUSTOMER.ID_USER_CHANGE;
    }

    @Override
    public UShort component1() {
        return getIdCustomer();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getSurname();
    }

    @Override
    public LocalDateTime component4() {
        return getBirthday();
    }

    @Override
    public LocalDateTime component5() {
        return getChanged();
    }

    @Override
    public UShort component6() {
        return getIdUserChange();
    }

    @Override
    public UShort value1() {
        return getIdCustomer();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getSurname();
    }

    @Override
    public LocalDateTime value4() {
        return getBirthday();
    }

    @Override
    public LocalDateTime value5() {
        return getChanged();
    }

    @Override
    public UShort value6() {
        return getIdUserChange();
    }

    @Override
    public AmCustomerRecord value1(UShort value) {
        setIdCustomer(value);
        return this;
    }

    @Override
    public AmCustomerRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public AmCustomerRecord value3(String value) {
        setSurname(value);
        return this;
    }

    @Override
    public AmCustomerRecord value4(LocalDateTime value) {
        setBirthday(value);
        return this;
    }

    @Override
    public AmCustomerRecord value5(LocalDateTime value) {
        setChanged(value);
        return this;
    }

    @Override
    public AmCustomerRecord value6(UShort value) {
        setIdUserChange(value);
        return this;
    }

    @Override
    public AmCustomerRecord values(UShort value1, String value2, String value3, LocalDateTime value4, LocalDateTime value5, UShort value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AmCustomerRecord
     */
    public AmCustomerRecord() {
        super(AmCustomer.AM_CUSTOMER);
    }

    /**
     * Create a detached, initialised AmCustomerRecord
     */
    public AmCustomerRecord(UShort idCustomer, String name, String surname, LocalDateTime birthday, LocalDateTime changed, UShort idUserChange) {
        super(AmCustomer.AM_CUSTOMER);

        setIdCustomer(idCustomer);
        setName(name);
        setSurname(surname);
        setBirthday(birthday);
        setChanged(changed);
        setIdUserChange(idUserChange);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised AmCustomerRecord
     */
    public AmCustomerRecord(com.allane.mobility.persistence.tables.pojos.AmCustomer value) {
        super(AmCustomer.AM_CUSTOMER);

        if (value != null) {
            setIdCustomer(value.getIdCustomer());
            setName(value.getName());
            setSurname(value.getSurname());
            setBirthday(value.getBirthday());
            setChanged(value.getChanged());
            setIdUserChange(value.getIdUserChange());
            resetChangedOnNotNull();
        }
    }
}
