/*
 * This file is generated by jOOQ.
 */
package com.allane.mobility.persistence.tables.records;


import com.allane.mobility.persistence.tables.AmCustomerLeasingContract;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AmCustomerLeasingContractRecord extends UpdatableRecordImpl<AmCustomerLeasingContractRecord> implements Record4<UShort, UShort, LocalDateTime, UShort> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>allmob.am_customer_leasing_contract.ID_customer</code>.
     */
    public void setIdCustomer(UShort value) {
        set(0, value);
    }

    /**
     * Getter for <code>allmob.am_customer_leasing_contract.ID_customer</code>.
     */
    public UShort getIdCustomer() {
        return (UShort) get(0);
    }

    /**
     * Setter for
     * <code>allmob.am_customer_leasing_contract.ID_contract_number</code>.
     */
    public void setIdContractNumber(UShort value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>allmob.am_customer_leasing_contract.ID_contract_number</code>.
     */
    public UShort getIdContractNumber() {
        return (UShort) get(1);
    }

    /**
     * Setter for <code>allmob.am_customer_leasing_contract.changed</code>.
     */
    public void setChanged(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>allmob.am_customer_leasing_contract.changed</code>.
     */
    public LocalDateTime getChanged() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for
     * <code>allmob.am_customer_leasing_contract.ID_user_change</code>.
     */
    public void setIdUserChange(UShort value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>allmob.am_customer_leasing_contract.ID_user_change</code>.
     */
    public UShort getIdUserChange() {
        return (UShort) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UShort, UShort> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<UShort, UShort, LocalDateTime, UShort> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<UShort, UShort, LocalDateTime, UShort> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<UShort> field1() {
        return AmCustomerLeasingContract.AM_CUSTOMER_LEASING_CONTRACT.ID_CUSTOMER;
    }

    @Override
    public Field<UShort> field2() {
        return AmCustomerLeasingContract.AM_CUSTOMER_LEASING_CONTRACT.ID_CONTRACT_NUMBER;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return AmCustomerLeasingContract.AM_CUSTOMER_LEASING_CONTRACT.CHANGED;
    }

    @Override
    public Field<UShort> field4() {
        return AmCustomerLeasingContract.AM_CUSTOMER_LEASING_CONTRACT.ID_USER_CHANGE;
    }

    @Override
    public UShort component1() {
        return getIdCustomer();
    }

    @Override
    public UShort component2() {
        return getIdContractNumber();
    }

    @Override
    public LocalDateTime component3() {
        return getChanged();
    }

    @Override
    public UShort component4() {
        return getIdUserChange();
    }

    @Override
    public UShort value1() {
        return getIdCustomer();
    }

    @Override
    public UShort value2() {
        return getIdContractNumber();
    }

    @Override
    public LocalDateTime value3() {
        return getChanged();
    }

    @Override
    public UShort value4() {
        return getIdUserChange();
    }

    @Override
    public AmCustomerLeasingContractRecord value1(UShort value) {
        setIdCustomer(value);
        return this;
    }

    @Override
    public AmCustomerLeasingContractRecord value2(UShort value) {
        setIdContractNumber(value);
        return this;
    }

    @Override
    public AmCustomerLeasingContractRecord value3(LocalDateTime value) {
        setChanged(value);
        return this;
    }

    @Override
    public AmCustomerLeasingContractRecord value4(UShort value) {
        setIdUserChange(value);
        return this;
    }

    @Override
    public AmCustomerLeasingContractRecord values(UShort value1, UShort value2, LocalDateTime value3, UShort value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AmCustomerLeasingContractRecord
     */
    public AmCustomerLeasingContractRecord() {
        super(AmCustomerLeasingContract.AM_CUSTOMER_LEASING_CONTRACT);
    }

    /**
     * Create a detached, initialised AmCustomerLeasingContractRecord
     */
    public AmCustomerLeasingContractRecord(UShort idCustomer, UShort idContractNumber, LocalDateTime changed, UShort idUserChange) {
        super(AmCustomerLeasingContract.AM_CUSTOMER_LEASING_CONTRACT);

        setIdCustomer(idCustomer);
        setIdContractNumber(idContractNumber);
        setChanged(changed);
        setIdUserChange(idUserChange);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised AmCustomerLeasingContractRecord
     */
    public AmCustomerLeasingContractRecord(com.allane.mobility.persistence.tables.pojos.AmCustomerLeasingContract value) {
        super(AmCustomerLeasingContract.AM_CUSTOMER_LEASING_CONTRACT);

        if (value != null) {
            setIdCustomer(value.getIdCustomer());
            setIdContractNumber(value.getIdContractNumber());
            setChanged(value.getChanged());
            setIdUserChange(value.getIdUserChange());
            resetChangedOnNotNull();
        }
    }
}
