/*
 * This file is generated by jOOQ.
 */
package com.allane.mobility.persistence.tables.daos;


import com.allane.mobility.persistence.tables.AmCustomerLeasingContract;
import com.allane.mobility.persistence.tables.records.AmCustomerLeasingContractRecord;

import java.time.LocalDateTime;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AmCustomerLeasingContractDao extends DAOImpl<AmCustomerLeasingContractRecord, com.allane.mobility.persistence.tables.pojos.AmCustomerLeasingContract, Record2<UShort, UShort>> {

    /**
     * Create a new AmCustomerLeasingContractDao without any configuration
     */
    public AmCustomerLeasingContractDao() {
        super(AmCustomerLeasingContract.AM_CUSTOMER_LEASING_CONTRACT, com.allane.mobility.persistence.tables.pojos.AmCustomerLeasingContract.class);
    }

    /**
     * Create a new AmCustomerLeasingContractDao with an attached configuration
     */
    public AmCustomerLeasingContractDao(Configuration configuration) {
        super(AmCustomerLeasingContract.AM_CUSTOMER_LEASING_CONTRACT, com.allane.mobility.persistence.tables.pojos.AmCustomerLeasingContract.class, configuration);
    }

    @Override
    public Record2<UShort, UShort> getId(com.allane.mobility.persistence.tables.pojos.AmCustomerLeasingContract object) {
        return compositeKeyRecord(object.getIdCustomer(), object.getIdContractNumber());
    }

    /**
     * Fetch records that have <code>ID_customer BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.allane.mobility.persistence.tables.pojos.AmCustomerLeasingContract> fetchRangeOfIdCustomer(UShort lowerInclusive, UShort upperInclusive) {
        return fetchRange(AmCustomerLeasingContract.AM_CUSTOMER_LEASING_CONTRACT.ID_CUSTOMER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>ID_customer IN (values)</code>
     */
    public List<com.allane.mobility.persistence.tables.pojos.AmCustomerLeasingContract> fetchByIdCustomer(UShort... values) {
        return fetch(AmCustomerLeasingContract.AM_CUSTOMER_LEASING_CONTRACT.ID_CUSTOMER, values);
    }

    /**
     * Fetch records that have <code>ID_contract_number BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.allane.mobility.persistence.tables.pojos.AmCustomerLeasingContract> fetchRangeOfIdContractNumber(UShort lowerInclusive, UShort upperInclusive) {
        return fetchRange(AmCustomerLeasingContract.AM_CUSTOMER_LEASING_CONTRACT.ID_CONTRACT_NUMBER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>ID_contract_number IN (values)</code>
     */
    public List<com.allane.mobility.persistence.tables.pojos.AmCustomerLeasingContract> fetchByIdContractNumber(UShort... values) {
        return fetch(AmCustomerLeasingContract.AM_CUSTOMER_LEASING_CONTRACT.ID_CONTRACT_NUMBER, values);
    }

    /**
     * Fetch records that have <code>changed BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.allane.mobility.persistence.tables.pojos.AmCustomerLeasingContract> fetchRangeOfChanged(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(AmCustomerLeasingContract.AM_CUSTOMER_LEASING_CONTRACT.CHANGED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>changed IN (values)</code>
     */
    public List<com.allane.mobility.persistence.tables.pojos.AmCustomerLeasingContract> fetchByChanged(LocalDateTime... values) {
        return fetch(AmCustomerLeasingContract.AM_CUSTOMER_LEASING_CONTRACT.CHANGED, values);
    }

    /**
     * Fetch records that have <code>ID_user_change BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.allane.mobility.persistence.tables.pojos.AmCustomerLeasingContract> fetchRangeOfIdUserChange(UShort lowerInclusive, UShort upperInclusive) {
        return fetchRange(AmCustomerLeasingContract.AM_CUSTOMER_LEASING_CONTRACT.ID_USER_CHANGE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>ID_user_change IN (values)</code>
     */
    public List<com.allane.mobility.persistence.tables.pojos.AmCustomerLeasingContract> fetchByIdUserChange(UShort... values) {
        return fetch(AmCustomerLeasingContract.AM_CUSTOMER_LEASING_CONTRACT.ID_USER_CHANGE, values);
    }
}
