/*
 * This file is generated by jOOQ.
 */
package com.allane.mobility.persistence.tables.daos;


import com.allane.mobility.persistence.tables.AmVehicle;
import com.allane.mobility.persistence.tables.records.AmVehicleRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UByte;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AmVehicleDao extends DAOImpl<AmVehicleRecord, com.allane.mobility.persistence.tables.pojos.AmVehicle, UShort> {

    /**
     * Create a new AmVehicleDao without any configuration
     */
    public AmVehicleDao() {
        super(AmVehicle.AM_VEHICLE, com.allane.mobility.persistence.tables.pojos.AmVehicle.class);
    }

    /**
     * Create a new AmVehicleDao with an attached configuration
     */
    public AmVehicleDao(Configuration configuration) {
        super(AmVehicle.AM_VEHICLE, com.allane.mobility.persistence.tables.pojos.AmVehicle.class, configuration);
    }

    @Override
    public UShort getId(com.allane.mobility.persistence.tables.pojos.AmVehicle object) {
        return object.getIdVehicle();
    }

    /**
     * Fetch records that have <code>ID_vehicle BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.allane.mobility.persistence.tables.pojos.AmVehicle> fetchRangeOfIdVehicle(UShort lowerInclusive, UShort upperInclusive) {
        return fetchRange(AmVehicle.AM_VEHICLE.ID_VEHICLE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>ID_vehicle IN (values)</code>
     */
    public List<com.allane.mobility.persistence.tables.pojos.AmVehicle> fetchByIdVehicle(UShort... values) {
        return fetch(AmVehicle.AM_VEHICLE.ID_VEHICLE, values);
    }

    /**
     * Fetch a unique record that has <code>ID_vehicle = value</code>
     */
    public com.allane.mobility.persistence.tables.pojos.AmVehicle fetchOneByIdVehicle(UShort value) {
        return fetchOne(AmVehicle.AM_VEHICLE.ID_VEHICLE, value);
    }

    /**
     * Fetch a unique record that has <code>ID_vehicle = value</code>
     */
    public Optional<com.allane.mobility.persistence.tables.pojos.AmVehicle> fetchOptionalByIdVehicle(UShort value) {
        return fetchOptional(AmVehicle.AM_VEHICLE.ID_VEHICLE, value);
    }

    /**
     * Fetch records that have <code>brand BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.allane.mobility.persistence.tables.pojos.AmVehicle> fetchRangeOfBrand(String lowerInclusive, String upperInclusive) {
        return fetchRange(AmVehicle.AM_VEHICLE.BRAND, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>brand IN (values)</code>
     */
    public List<com.allane.mobility.persistence.tables.pojos.AmVehicle> fetchByBrand(String... values) {
        return fetch(AmVehicle.AM_VEHICLE.BRAND, values);
    }

    /**
     * Fetch records that have <code>model BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.allane.mobility.persistence.tables.pojos.AmVehicle> fetchRangeOfModel(String lowerInclusive, String upperInclusive) {
        return fetchRange(AmVehicle.AM_VEHICLE.MODEL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>model IN (values)</code>
     */
    public List<com.allane.mobility.persistence.tables.pojos.AmVehicle> fetchByModel(String... values) {
        return fetch(AmVehicle.AM_VEHICLE.MODEL, values);
    }

    /**
     * Fetch records that have <code>model_year BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.allane.mobility.persistence.tables.pojos.AmVehicle> fetchRangeOfModelYear(UByte lowerInclusive, UByte upperInclusive) {
        return fetchRange(AmVehicle.AM_VEHICLE.MODEL_YEAR, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>model_year IN (values)</code>
     */
    public List<com.allane.mobility.persistence.tables.pojos.AmVehicle> fetchByModelYear(UByte... values) {
        return fetch(AmVehicle.AM_VEHICLE.MODEL_YEAR, values);
    }

    /**
     * Fetch records that have <code>vin_code BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.allane.mobility.persistence.tables.pojos.AmVehicle> fetchRangeOfVinCode(String lowerInclusive, String upperInclusive) {
        return fetchRange(AmVehicle.AM_VEHICLE.VIN_CODE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>vin_code IN (values)</code>
     */
    public List<com.allane.mobility.persistence.tables.pojos.AmVehicle> fetchByVinCode(String... values) {
        return fetch(AmVehicle.AM_VEHICLE.VIN_CODE, values);
    }

    /**
     * Fetch records that have <code>price BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.allane.mobility.persistence.tables.pojos.AmVehicle> fetchRangeOfPrice(BigDecimal lowerInclusive, BigDecimal upperInclusive) {
        return fetchRange(AmVehicle.AM_VEHICLE.PRICE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>price IN (values)</code>
     */
    public List<com.allane.mobility.persistence.tables.pojos.AmVehicle> fetchByPrice(BigDecimal... values) {
        return fetch(AmVehicle.AM_VEHICLE.PRICE, values);
    }

    /**
     * Fetch records that have <code>changed BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.allane.mobility.persistence.tables.pojos.AmVehicle> fetchRangeOfChanged(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(AmVehicle.AM_VEHICLE.CHANGED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>changed IN (values)</code>
     */
    public List<com.allane.mobility.persistence.tables.pojos.AmVehicle> fetchByChanged(LocalDateTime... values) {
        return fetch(AmVehicle.AM_VEHICLE.CHANGED, values);
    }

    /**
     * Fetch records that have <code>ID_user_change BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.allane.mobility.persistence.tables.pojos.AmVehicle> fetchRangeOfIdUserChange(UShort lowerInclusive, UShort upperInclusive) {
        return fetchRange(AmVehicle.AM_VEHICLE.ID_USER_CHANGE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>ID_user_change IN (values)</code>
     */
    public List<com.allane.mobility.persistence.tables.pojos.AmVehicle> fetchByIdUserChange(UShort... values) {
        return fetch(AmVehicle.AM_VEHICLE.ID_USER_CHANGE, values);
    }
}
