/*
 * This file is generated by jOOQ.
 */
package com.allane.mobility.persistence.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AmCustomer implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer idCustomer;
    private String name;
    private String surname;
    private LocalDateTime birthday;
    private LocalDateTime changed;
    private Integer idUserChange;

    public AmCustomer() {}

    public AmCustomer(AmCustomer value) {
        this.idCustomer = value.idCustomer;
        this.name = value.name;
        this.surname = value.surname;
        this.birthday = value.birthday;
        this.changed = value.changed;
        this.idUserChange = value.idUserChange;
    }

    public AmCustomer(
        Integer idCustomer,
        String name,
        String surname,
        LocalDateTime birthday,
        LocalDateTime changed,
        Integer idUserChange
    ) {
        this.idCustomer = idCustomer;
        this.name = name;
        this.surname = surname;
        this.birthday = birthday;
        this.changed = changed;
        this.idUserChange = idUserChange;
    }

    /**
     * Getter for <code>allmob.am_customer.ID_customer</code>.
     */
    public Integer getIdCustomer() {
        return this.idCustomer;
    }

    /**
     * Setter for <code>allmob.am_customer.ID_customer</code>.
     */
    public void setIdCustomer(Integer idCustomer) {
        this.idCustomer = idCustomer;
    }

    /**
     * Getter for <code>allmob.am_customer.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>allmob.am_customer.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>allmob.am_customer.surname</code>.
     */
    public String getSurname() {
        return this.surname;
    }

    /**
     * Setter for <code>allmob.am_customer.surname</code>.
     */
    public void setSurname(String surname) {
        this.surname = surname;
    }

    /**
     * Getter for <code>allmob.am_customer.birthday</code>.
     */
    public LocalDateTime getBirthday() {
        return this.birthday;
    }

    /**
     * Setter for <code>allmob.am_customer.birthday</code>.
     */
    public void setBirthday(LocalDateTime birthday) {
        this.birthday = birthday;
    }

    /**
     * Getter for <code>allmob.am_customer.changed</code>.
     */
    public LocalDateTime getChanged() {
        return this.changed;
    }

    /**
     * Setter for <code>allmob.am_customer.changed</code>.
     */
    public void setChanged(LocalDateTime changed) {
        this.changed = changed;
    }

    /**
     * Getter for <code>allmob.am_customer.ID_user_change</code>.
     */
    public Integer getIdUserChange() {
        return this.idUserChange;
    }

    /**
     * Setter for <code>allmob.am_customer.ID_user_change</code>.
     */
    public void setIdUserChange(Integer idUserChange) {
        this.idUserChange = idUserChange;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final AmCustomer other = (AmCustomer) obj;
        if (this.idCustomer == null) {
            if (other.idCustomer != null)
                return false;
        }
        else if (!this.idCustomer.equals(other.idCustomer))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.surname == null) {
            if (other.surname != null)
                return false;
        }
        else if (!this.surname.equals(other.surname))
            return false;
        if (this.birthday == null) {
            if (other.birthday != null)
                return false;
        }
        else if (!this.birthday.equals(other.birthday))
            return false;
        if (this.changed == null) {
            if (other.changed != null)
                return false;
        }
        else if (!this.changed.equals(other.changed))
            return false;
        if (this.idUserChange == null) {
            if (other.idUserChange != null)
                return false;
        }
        else if (!this.idUserChange.equals(other.idUserChange))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.idCustomer == null) ? 0 : this.idCustomer.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.surname == null) ? 0 : this.surname.hashCode());
        result = prime * result + ((this.birthday == null) ? 0 : this.birthday.hashCode());
        result = prime * result + ((this.changed == null) ? 0 : this.changed.hashCode());
        result = prime * result + ((this.idUserChange == null) ? 0 : this.idUserChange.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AmCustomer (");

        sb.append(idCustomer);
        sb.append(", ").append(name);
        sb.append(", ").append(surname);
        sb.append(", ").append(birthday);
        sb.append(", ").append(changed);
        sb.append(", ").append(idUserChange);

        sb.append(")");
        return sb.toString();
    }
}
