/*
 * This file is generated by jOOQ.
 */
package com.allane.mobility.persistence.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AmLeasingContract implements Serializable {

    private static final long serialVersionUID = 1L;

    private UShort idContractNumber;
    private UShort idVehicle;
    private BigDecimal monthlyRate;
    private LocalDateTime changed;
    private UShort idUserChange;

    public AmLeasingContract() {}

    public AmLeasingContract(AmLeasingContract value) {
        this.idContractNumber = value.idContractNumber;
        this.idVehicle = value.idVehicle;
        this.monthlyRate = value.monthlyRate;
        this.changed = value.changed;
        this.idUserChange = value.idUserChange;
    }

    public AmLeasingContract(
        UShort idContractNumber,
        UShort idVehicle,
        BigDecimal monthlyRate,
        LocalDateTime changed,
        UShort idUserChange
    ) {
        this.idContractNumber = idContractNumber;
        this.idVehicle = idVehicle;
        this.monthlyRate = monthlyRate;
        this.changed = changed;
        this.idUserChange = idUserChange;
    }

    /**
     * Getter for <code>allmob.am_leasing_contract.ID_contract_number</code>.
     */
    public UShort getIdContractNumber() {
        return this.idContractNumber;
    }

    /**
     * Setter for <code>allmob.am_leasing_contract.ID_contract_number</code>.
     */
    public void setIdContractNumber(UShort idContractNumber) {
        this.idContractNumber = idContractNumber;
    }

    /**
     * Getter for <code>allmob.am_leasing_contract.ID_vehicle</code>.
     */
    public UShort getIdVehicle() {
        return this.idVehicle;
    }

    /**
     * Setter for <code>allmob.am_leasing_contract.ID_vehicle</code>.
     */
    public void setIdVehicle(UShort idVehicle) {
        this.idVehicle = idVehicle;
    }

    /**
     * Getter for <code>allmob.am_leasing_contract.monthly_rate</code>.
     */
    public BigDecimal getMonthlyRate() {
        return this.monthlyRate;
    }

    /**
     * Setter for <code>allmob.am_leasing_contract.monthly_rate</code>.
     */
    public void setMonthlyRate(BigDecimal monthlyRate) {
        this.monthlyRate = monthlyRate;
    }

    /**
     * Getter for <code>allmob.am_leasing_contract.changed</code>.
     */
    public LocalDateTime getChanged() {
        return this.changed;
    }

    /**
     * Setter for <code>allmob.am_leasing_contract.changed</code>.
     */
    public void setChanged(LocalDateTime changed) {
        this.changed = changed;
    }

    /**
     * Getter for <code>allmob.am_leasing_contract.ID_user_change</code>.
     */
    public UShort getIdUserChange() {
        return this.idUserChange;
    }

    /**
     * Setter for <code>allmob.am_leasing_contract.ID_user_change</code>.
     */
    public void setIdUserChange(UShort idUserChange) {
        this.idUserChange = idUserChange;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final AmLeasingContract other = (AmLeasingContract) obj;
        if (this.idContractNumber == null) {
            if (other.idContractNumber != null)
                return false;
        }
        else if (!this.idContractNumber.equals(other.idContractNumber))
            return false;
        if (this.idVehicle == null) {
            if (other.idVehicle != null)
                return false;
        }
        else if (!this.idVehicle.equals(other.idVehicle))
            return false;
        if (this.monthlyRate == null) {
            if (other.monthlyRate != null)
                return false;
        }
        else if (!this.monthlyRate.equals(other.monthlyRate))
            return false;
        if (this.changed == null) {
            if (other.changed != null)
                return false;
        }
        else if (!this.changed.equals(other.changed))
            return false;
        if (this.idUserChange == null) {
            if (other.idUserChange != null)
                return false;
        }
        else if (!this.idUserChange.equals(other.idUserChange))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.idContractNumber == null) ? 0 : this.idContractNumber.hashCode());
        result = prime * result + ((this.idVehicle == null) ? 0 : this.idVehicle.hashCode());
        result = prime * result + ((this.monthlyRate == null) ? 0 : this.monthlyRate.hashCode());
        result = prime * result + ((this.changed == null) ? 0 : this.changed.hashCode());
        result = prime * result + ((this.idUserChange == null) ? 0 : this.idUserChange.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AmLeasingContract (");

        sb.append(idContractNumber);
        sb.append(", ").append(idVehicle);
        sb.append(", ").append(monthlyRate);
        sb.append(", ").append(changed);
        sb.append(", ").append(idUserChange);

        sb.append(")");
        return sb.toString();
    }
}
