/*
 * This file is generated by jOOQ.
 */
package com.allane.mobility.persistence.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.types.UByte;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AmVehicle implements Serializable {

    private static final long serialVersionUID = 1L;

    private UShort idVehicle;
    private String brand;
    private String model;
    private UByte modelYear;
    private String vinCode;
    private BigDecimal price;
    private LocalDateTime changed;
    private UShort idUserChange;

    public AmVehicle() {}

    public AmVehicle(AmVehicle value) {
        this.idVehicle = value.idVehicle;
        this.brand = value.brand;
        this.model = value.model;
        this.modelYear = value.modelYear;
        this.vinCode = value.vinCode;
        this.price = value.price;
        this.changed = value.changed;
        this.idUserChange = value.idUserChange;
    }

    public AmVehicle(
        UShort idVehicle,
        String brand,
        String model,
        UByte modelYear,
        String vinCode,
        BigDecimal price,
        LocalDateTime changed,
        UShort idUserChange
    ) {
        this.idVehicle = idVehicle;
        this.brand = brand;
        this.model = model;
        this.modelYear = modelYear;
        this.vinCode = vinCode;
        this.price = price;
        this.changed = changed;
        this.idUserChange = idUserChange;
    }

    /**
     * Getter for <code>allmob.am_vehicle.ID_vehicle</code>.
     */
    public UShort getIdVehicle() {
        return this.idVehicle;
    }

    /**
     * Setter for <code>allmob.am_vehicle.ID_vehicle</code>.
     */
    public void setIdVehicle(UShort idVehicle) {
        this.idVehicle = idVehicle;
    }

    /**
     * Getter for <code>allmob.am_vehicle.brand</code>.
     */
    public String getBrand() {
        return this.brand;
    }

    /**
     * Setter for <code>allmob.am_vehicle.brand</code>.
     */
    public void setBrand(String brand) {
        this.brand = brand;
    }

    /**
     * Getter for <code>allmob.am_vehicle.model</code>.
     */
    public String getModel() {
        return this.model;
    }

    /**
     * Setter for <code>allmob.am_vehicle.model</code>.
     */
    public void setModel(String model) {
        this.model = model;
    }

    /**
     * Getter for <code>allmob.am_vehicle.model_year</code>.
     */
    public UByte getModelYear() {
        return this.modelYear;
    }

    /**
     * Setter for <code>allmob.am_vehicle.model_year</code>.
     */
    public void setModelYear(UByte modelYear) {
        this.modelYear = modelYear;
    }

    /**
     * Getter for <code>allmob.am_vehicle.vin_code</code>.
     */
    public String getVinCode() {
        return this.vinCode;
    }

    /**
     * Setter for <code>allmob.am_vehicle.vin_code</code>.
     */
    public void setVinCode(String vinCode) {
        this.vinCode = vinCode;
    }

    /**
     * Getter for <code>allmob.am_vehicle.price</code>.
     */
    public BigDecimal getPrice() {
        return this.price;
    }

    /**
     * Setter for <code>allmob.am_vehicle.price</code>.
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * Getter for <code>allmob.am_vehicle.changed</code>.
     */
    public LocalDateTime getChanged() {
        return this.changed;
    }

    /**
     * Setter for <code>allmob.am_vehicle.changed</code>.
     */
    public void setChanged(LocalDateTime changed) {
        this.changed = changed;
    }

    /**
     * Getter for <code>allmob.am_vehicle.ID_user_change</code>.
     */
    public UShort getIdUserChange() {
        return this.idUserChange;
    }

    /**
     * Setter for <code>allmob.am_vehicle.ID_user_change</code>.
     */
    public void setIdUserChange(UShort idUserChange) {
        this.idUserChange = idUserChange;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final AmVehicle other = (AmVehicle) obj;
        if (this.idVehicle == null) {
            if (other.idVehicle != null)
                return false;
        }
        else if (!this.idVehicle.equals(other.idVehicle))
            return false;
        if (this.brand == null) {
            if (other.brand != null)
                return false;
        }
        else if (!this.brand.equals(other.brand))
            return false;
        if (this.model == null) {
            if (other.model != null)
                return false;
        }
        else if (!this.model.equals(other.model))
            return false;
        if (this.modelYear == null) {
            if (other.modelYear != null)
                return false;
        }
        else if (!this.modelYear.equals(other.modelYear))
            return false;
        if (this.vinCode == null) {
            if (other.vinCode != null)
                return false;
        }
        else if (!this.vinCode.equals(other.vinCode))
            return false;
        if (this.price == null) {
            if (other.price != null)
                return false;
        }
        else if (!this.price.equals(other.price))
            return false;
        if (this.changed == null) {
            if (other.changed != null)
                return false;
        }
        else if (!this.changed.equals(other.changed))
            return false;
        if (this.idUserChange == null) {
            if (other.idUserChange != null)
                return false;
        }
        else if (!this.idUserChange.equals(other.idUserChange))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.idVehicle == null) ? 0 : this.idVehicle.hashCode());
        result = prime * result + ((this.brand == null) ? 0 : this.brand.hashCode());
        result = prime * result + ((this.model == null) ? 0 : this.model.hashCode());
        result = prime * result + ((this.modelYear == null) ? 0 : this.modelYear.hashCode());
        result = prime * result + ((this.vinCode == null) ? 0 : this.vinCode.hashCode());
        result = prime * result + ((this.price == null) ? 0 : this.price.hashCode());
        result = prime * result + ((this.changed == null) ? 0 : this.changed.hashCode());
        result = prime * result + ((this.idUserChange == null) ? 0 : this.idUserChange.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AmVehicle (");

        sb.append(idVehicle);
        sb.append(", ").append(brand);
        sb.append(", ").append(model);
        sb.append(", ").append(modelYear);
        sb.append(", ").append(vinCode);
        sb.append(", ").append(price);
        sb.append(", ").append(changed);
        sb.append(", ").append(idUserChange);

        sb.append(")");
        return sb.toString();
    }
}
