/*
 * This file is generated by jOOQ.
 */
package com.allane.mobility.persistence.tables;


import com.allane.mobility.persistence.Allmob;
import com.allane.mobility.persistence.Indexes;
import com.allane.mobility.persistence.Keys;
import com.allane.mobility.persistence.tables.records.AmCustomerRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function6;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AmCustomer extends TableImpl<AmCustomerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>allmob.am_customer</code>
     */
    public static final AmCustomer AM_CUSTOMER = new AmCustomer();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AmCustomerRecord> getRecordType() {
        return AmCustomerRecord.class;
    }

    /**
     * The column <code>allmob.am_customer.ID_customer</code>.
     */
    public final TableField<AmCustomerRecord, Integer> ID_CUSTOMER = createField(DSL.name("ID_customer"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>allmob.am_customer.name</code>.
     */
    public final TableField<AmCustomerRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>allmob.am_customer.surname</code>.
     */
    public final TableField<AmCustomerRecord, String> SURNAME = createField(DSL.name("surname"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>allmob.am_customer.birthday</code>.
     */
    public final TableField<AmCustomerRecord, LocalDateTime> BIRTHDAY = createField(DSL.name("birthday"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column <code>allmob.am_customer.changed</code>.
     */
    public final TableField<AmCustomerRecord, LocalDateTime> CHANGED = createField(DSL.name("changed"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>allmob.am_customer.ID_user_change</code>.
     */
    public final TableField<AmCustomerRecord, Integer> ID_USER_CHANGE = createField(DSL.name("ID_user_change"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.INTEGER)), this, "");

    private AmCustomer(Name alias, Table<AmCustomerRecord> aliased) {
        this(alias, aliased, null);
    }

    private AmCustomer(Name alias, Table<AmCustomerRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>allmob.am_customer</code> table reference
     */
    public AmCustomer(String alias) {
        this(DSL.name(alias), AM_CUSTOMER);
    }

    /**
     * Create an aliased <code>allmob.am_customer</code> table reference
     */
    public AmCustomer(Name alias) {
        this(alias, AM_CUSTOMER);
    }

    /**
     * Create a <code>allmob.am_customer</code> table reference
     */
    public AmCustomer() {
        this(DSL.name("am_customer"), null);
    }

    public <O extends Record> AmCustomer(Table<O> child, ForeignKey<O, AmCustomerRecord> key) {
        super(child, key, AM_CUSTOMER);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Allmob.ALLMOB;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.AM_CUSTOMER_INDX_AM_USER);
    }

    @Override
    public UniqueKey<AmCustomerRecord> getPrimaryKey() {
        return Keys.KEY_AM_CUSTOMER_PRIMARY;
    }

    @Override
    public AmCustomer as(String alias) {
        return new AmCustomer(DSL.name(alias), this);
    }

    @Override
    public AmCustomer as(Name alias) {
        return new AmCustomer(alias, this);
    }

    @Override
    public AmCustomer as(Table<?> alias) {
        return new AmCustomer(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AmCustomer rename(String name) {
        return new AmCustomer(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AmCustomer rename(Name name) {
        return new AmCustomer(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AmCustomer rename(Table<?> name) {
        return new AmCustomer(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, String, LocalDateTime, LocalDateTime, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function6<? super Integer, ? super String, ? super String, ? super LocalDateTime, ? super LocalDateTime, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function6<? super Integer, ? super String, ? super String, ? super LocalDateTime, ? super LocalDateTime, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
